//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace musicDL.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("musicDL.Resources.Message", typeof(Message).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   All processes have been completed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string allCoplete {
            get {
                return ResourceManager.GetString("allCoplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   artist に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string artist {
            get {
                return ResourceManager.GetString("artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   authentication URL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string authURL {
            get {
                return ResourceManager.GetString("authURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process multiple audio files in a directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchCommandDescription {
            get {
                return ResourceManager.GetString("batchCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch conversions completed: successful {0}, failed {1} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchConversionResult {
            get {
                return ResourceManager.GetString("batchConversionResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert multiple audio files in a directory に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchConvertCommandDescription {
            get {
                return ResourceManager.GetString("batchConvertCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory containing audio files to convert に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchConvertDirArgDescription {
            get {
                return ResourceManager.GetString("batchConvertDirArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target audio format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchFormatOptionDescription {
            get {
                return ResourceManager.GetString("batchFormatOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Batch processing completed: Success {successful}, Failure {failed に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchProcessResult {
            get {
                return ResourceManager.GetString("batchProcessResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert multiple files and process with metadata/extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string batchTransformCommandDescription {
            get {
                return ResourceManager.GetString("batchTransformCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory containing audio files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string btfDirArgDescription {
            get {
                return ResourceManager.GetString("btfDirArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string complete {
            get {
                return ResourceManager.GetString("complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Complete に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string conversionComplete {
            get {
                return ResourceManager.GetString("conversionComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   conversion error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string conversionError {
            get {
                return ResourceManager.GetString("conversionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion Format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string conversionFormat {
            get {
                return ResourceManager.GetString("conversionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert audio file to different format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string convertCommandDescription {
            get {
                return ResourceManager.GetString("convertCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Converting {0} files to {1} format... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string convertingFiles {
            get {
                return ResourceManager.GetString("convertingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input audio file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string convertInputArgDescription {
            get {
                return ResourceManager.GetString("convertInputArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert {0} files to {1} format and perform metadata processing... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string convertProcessing {
            get {
                return ResourceManager.GetString("convertProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enable debug mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DebugOptionDescription {
            get {
                return ResourceManager.GetString("DebugOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default artist name for all files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string defaultArtistOptionDescription {
            get {
                return ResourceManager.GetString("defaultArtistOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory containing audio files to process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string directoryArgDescription {
            get {
                return ResourceManager.GetString("directoryArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Directory not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string directoryNotFound {
            get {
                return ResourceManager.GetString("directoryNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the Spotify track ID directly. or Enter to skip に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string enterTrackID {
            get {
                return ResourceManager.GetString("enterTrackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string fileNotFound {
            get {
                return ResourceManager.GetString("fileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Path to the audio file to process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string filePathArgDescription {
            get {
                return ResourceManager.GetString("filePathArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This is the first page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string firstPage {
            get {
                return ResourceManager.GetString("firstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Target audio format に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string formatOptionDescription {
            get {
                return ResourceManager.GetString("formatOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in process に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string inProcess {
            get {
                return ResourceManager.GetString("inProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy metadata from source file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string keepMetadataOptionDescription {
            get {
                return ResourceManager.GetString("keepMetadataOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Metadata update is complete. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string metadataComplete {
            get {
                return ResourceManager.GetString("metadataComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error occurred during metadata processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string metadataError {
            get {
                return ResourceManager.GetString("metadataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No convertible audio files were found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noConvertible {
            get {
                return ResourceManager.GetString("noConvertible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No more items に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noMoreItems {
            get {
                return ResourceManager.GetString("noMoreItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No processable audio files were found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noProcessableFile {
            get {
                return ResourceManager.GetString("noProcessableFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No search results found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string noResultSearch {
            get {
                return ResourceManager.GetString("noResultSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Could not retrieve the authorization code. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string notRetriveAuthCode {
            get {
                return ResourceManager.GetString("notRetriveAuthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file path (optional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string outputOptionDescription {
            get {
                return ResourceManager.GetString("outputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please complete the authentication in your browser... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pleaseCompAuth {
            get {
                return ResourceManager.GetString("pleaseCompAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Press &apos;s&apos; to skip sharing. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string pressStoSkip {
            get {
                return ResourceManager.GetString("pressStoSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process existing audio file with metadata に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string processCommandDescription {
            get {
                return ResourceManager.GetString("processCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Processing an existing file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string processExistingFile {
            get {
                return ResourceManager.GetString("processExistingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Music metadata manager - Process metadata, album art, and convert audio files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string RootCommandDescription {
            get {
                return ResourceManager.GetString("RootCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Running extensions... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string runExt {
            get {
                return ResourceManager.GetString("runExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Select the number of the song you want to apply or enter the track ID に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string selectTheNumber {
            get {
                return ResourceManager.GetString("selectTheNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sharing skipped by user. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string sharingSkip {
            get {
                return ResourceManager.GetString("sharingSkip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start file conversion に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string startConvert {
            get {
                return ResourceManager.GetString("startConvert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start conversion + metadata processing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string startConvPro {
            get {
                return ResourceManager.GetString("startConvPro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output file path (optional) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string tfOutputOptionDescription {
            get {
                return ResourceManager.GetString("tfOutputOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string title {
            get {
                return ResourceManager.GetString("title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Song title に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TitleOptionDescription {
            get {
                return ResourceManager.GetString("TitleOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The track ID format is invalid. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string trackIDInvalid {
            get {
                return ResourceManager.GetString("trackIDInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Track not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string trackNotFound {
            get {
                return ResourceManager.GetString("trackNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Convert audio file and process with metadata/extensions に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string transformCommandDescription {
            get {
                return ResourceManager.GetString("transformCommandDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input audio file path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string transformInputArgDescription {
            get {
                return ResourceManager.GetString("transformInputArgDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   unknown に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string unknown {
            get {
                return ResourceManager.GetString("unknown", resourceCulture);
            }
        }
    }
}
